import { User } from './user.model'


/**
 * @VAZNO
 *
 * U README-U SAM VEC REKAO DA CE        user      OBJEKAT, ILI USER Document
 *                                               BITI ZAKACENI REQUEST, STO CE URADITI MIDDLEWARE
 *                                                 KOJ ICU KASNIJE DEFINISATI
 *
 *  AKO NE MOZES DA WRAPPUJES SVOJ MIND AROUNDF IT TREBA DA SHVATIS DA MIDDLEWARE
 * IMA PRISTUP TVOM REQUEST-U
 *
 * PRE NEGO STO MOUNT-UJES ROUTER, TI CES MOUNT-OVATI I MIDDLEWARE
 * ISTI REQUEST PROLAZI I KROZ ROUTER I KROZ MIDDLEWARE
 *
 * MOZDA JE DOBRO DA PROVEZBAS OVO
 *
 */



