/**
 * @zasto SE OVAJ FAJ NAZIVA protected_server
 *
 * ZATO STO MI JE CILJ DA OVDE UPOTREBIM SVE MIDDLEWARWE-OVE KOJI VRSE VALIDACIJU TOKENA
 * JER ZA SVAKI VERB OVDE, ODNOSN OZA SVAKI ROUTE, KOJI BI SE DEFINISAO OVDE
 * MIDDLEWARE-OVI TREBA DA SE POSTARAJU DA IH SAMO KORISNIK SA VALIDNIM TOKENOM MOZE KORISTITI
 */